import streamlit as st
import pandas as pd
import json
import time

st.set_page_config(page_title="ICT Multi-Asset Cockpit", layout="wide")

# Auto-refresh tracking mechanism
if "run_count" not in st.session_state:
    st.session_state.run_count = 0
st.session_state.run_count += 1

st.title("⚡ ICT Multi-Index Trading Cockpit")
st.subheader("Live Institutional Sweep & Matrix Tracker")

def load_live_bot_states():
    """Safely reads the real-time state data generated by your trading bot script."""
    try:
        with open("dashboard_state.json", "r") as f:
            return json.load(f)
    except:
        return {}

# Load the fresh matrix data from the bot database
live_data = load_live_bot_states()

# --- MAIN SCANNER INTERFACE ---
st.header("📊 Multi-Asset Strategy Matrix")

assets = ["#US100_Z26", "#US30", "#US500_Z26"]
cols = st.columns(len(assets))

for i, asset in enumerate(assets):
    asset_state = live_data.get(asset, {"htf_bias": False, "bos_confirmed": False, "fvg_identified": False, "ifvg_triggered": False})
    
    with cols[i]:
        st.subheader(f"🔍 {asset}")
        
        st.checkbox(f"HTF Sweep Confirmed", value=asset_state["htf_bias"], key=f"htf_{asset}", disabled=True)
        st.checkbox(f"M5 Break of Structure", value=asset_state["bos_confirmed"], key=f"bos_{asset}", disabled=True)
        st.checkbox(f"M5 FVG Retested/Filled", value=asset_state["fvg_identified"], key=f"fvg_{asset}", disabled=True)
        st.checkbox(f"M1 iFVG Catalyst Triggered", value=asset_state["ifvg_triggered"], key=f"m1_{asset}", disabled=True)
        
        if asset_state["ifvg_triggered"]:
            st.success("🎯 Setup Triggered! Executing Order...")
        elif asset_state["htf_bias"]:
            st.warning("👀 HTF Sweep Active. Tracking Structure...")
        else:
            st.write("⚪ Scanning for liquidity sweeps...")
        st.markdown("---")

# Forces the cloud page dashboard layout screen to refresh every 5 seconds
time.sleep(5)
st.rerun()

